// AUTOGENERATED FROM CLDR DATA. DO NOT EDIT

package symbols

func init() {
	LongMonthNames[`en`] = []string{
		`---`,
		`January`,
		`February`,
		`March`,
		`April`,
		`May`,
		`June`,
		`July`,
		`August`,
		`September`,
		`October`,
		`November`,
		`December`,
	}

}
