// AUTOGENERATED FROM CLDR DATA. DO NOT EDIT

package symbols

func init() {
	ShortMonthNames[`es`] = []string{
		`---`,
		`ene.`,
		`feb.`,
		`mar.`,
		`abr.`,
		`may.`,
		`jun.`,
		`jul.`,
		`ago.`,
		`sept.`,
		`oct.`,
		`nov.`,
		`dic.`,
	}

	LongMonthNames[`es`] = []string{
		`---`,
		`enero`,
		`febrero`,
		`marzo`,
		`abril`,
		`mayo`,
		`junio`,
		`julio`,
		`agosto`,
		`septiembre`,
		`octubre`,
		`noviembre`,
		`diciembre`,
	}

}
