// AUTOGENERATED FROM CLDR DATA. DO NOT EDIT

package symbols

func init() {
	LongMonthNames[`es`] = []string{
		`---`,
		`enero`,
		`febrero`,
		`marzo`,
		`abril`,
		`mayo`,
		`junio`,
		`julio`,
		`agosto`,
		`septiembre`,
		`octubre`,
		`noviembre`,
		`diciembre`,
	}

}

