// AUTOGENERATED FROM CLDR DATA. DO NOT EDIT

package symbols

func init() {
	LongMonthNames[`fr`] = []string{
		`---`,
		`janvier`,
		`février`,
		`mars`,
		`avril`,
		`mai`,
		`juin`,
		`juillet`,
		`août`,
		`septembre`,
		`octobre`,
		`novembre`,
		`décembre`,
	}

}
