// AUTOGENERATED FROM CLDR DATA. DO NOT EDIT

package symbols

func init() {
	ShortMonthNames[`fr`] = []string{
		`---`,
		`janv.`,
		`févr.`,
		`mars`,
		`avr.`,
		`mai`,
		`juin`,
		`juil.`,
		`août`,
		`sept.`,
		`oct.`,
		`nov.`,
		`déc.`,
	}

	LongMonthNames[`fr`] = []string{
		`---`,
		`janvier`,
		`février`,
		`mars`,
		`avril`,
		`mai`,
		`juin`,
		`juillet`,
		`août`,
		`septembre`,
		`octobre`,
		`novembre`,
		`décembre`,
	}

}
