// AUTOGENERATED FROM CLDR DATA. DO NOT EDIT

package symbols

func init() {
	LongMonthNames[`ru`] = []string{
		`---`,
		`января`,
		`февраля`,
		`марта`,
		`апреля`,
		`мая`,
		`июня`,
		`июля`,
		`августа`,
		`сентября`,
		`октября`,
		`ноября`,
		`декабря`,
	}

}

